name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository.
        uses: actions/checkout@v4

      - name: Check if a build should be released.
        env:
            GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          if [[ "${{ github.event.head_commit.message }}" != *"release:"* ]]; then
            exit 1
          fi
  build:
    runs-on: windows-latest
    needs: checkout
    steps:
      - name: Install & setup MSYS2 environment.
        uses: msys2/setup-msys2@v2
        with: 
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-MinHook

      - name: Clone the target repository.
        uses: actions/checkout@v4

      - name: Build a new release with required UCRT64 packages.
        shell: msys2 {0}
        run: |
          ./Build.cmd
      
      - name: Check the CDN repository.
        uses: actions/checkout@v4
        with:
          repository: 'flarialmc/newcdn'
          ref: 'main'
          path: 'cdn'

      - name: Deploy a new release to the CDN.
        run: |
          cd "cdn"
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@example.com"

          cp "D:/a/bootstrapper/bootstrapper/bin/vcruntime140_1.dll" "./dll/bootstrapper.dll"
          git add "dll/bootstrapper.dll"
          git commit -a -m "Update Flarial Client Bootstrapper"
          git push origin main 