name: Build

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Check if a build should be released.
        uses: actions/checkout@v4

      - name: Check
        env:
            GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          if [[ "${{ github.event.head_commit.message }}" != *"release:"* ]]; then
            exit 1
          fi

  build:
    runs-on: windows-latest
    needs: checkout
    steps:
      - name: Install & setup MSYS2 environment.
        uses: msys2/setup-msys2@v2
        with: 
          update: true

      - name: Install required UCRT64 packages.
        shell: msys2 {0}
        run: |
          pacman -Syu mingw-w64-ucrt-x86_64-gcc mingw-w64-ucrt-x86_64-MinHook --noconfirm 

      - name: Build a new release.
        shell: msys2 {0} -ucrt64
        run: |
          uname -a
          gcc
